In [3]:
import numpy as np

In [4]:
a= np.arrange(10,100)

AttributeError: module 'numpy' has no attribute 'arrange'

In [13]:
#create a 3x3 matrix
np.arange(9).reshape(3,3)/3

array([[0.        , 0.33333333, 0.66666667],
       [1.        , 1.33333333, 1.66666667],
       [2.        , 2.33333333, 2.66666667]])

In [9]:
np.random.randn(25)

array([-1.34511355, -0.35884038,  0.35033956, -0.07455327,  1.23443675,
        0.35713287, -0.37780911,  1.54291325, -1.98622135, -0.83982992,
       -0.92399024, -0.73076634, -0.7688629 , -0.22111887, -0.38086423,
       -1.20338643, -1.11941476,  0.3375937 ,  0.85387873,  0.05241012,
        1.03284665, -0.85689854,  0.26909317, -1.56573143,  0.98824201])

In [14]:
np.arange(0.01)

array([0.])

In [15]:
np.linespace(0,1,20)

AttributeError: module 'numpy' has no attribute 'linespace'

In [17]:
b = np.arange(1,26).reshape(5,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
b[2:1:]

array([], shape=(0, 5), dtype=int32)

In [22]:
b[:,1:].sum(axis=1)

array([14, 34, 54, 74, 94])