In [2]:
import numpy as np

In [10]:

d = np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[3,31],[1,11],[5,51]]])
d

array([[[ 4, 41],
        [ 8, 81],
        [ 7, 71]],

       [[ 3, 31],
        [ 1, 11],
        [ 5, 51]],

       [[ 3, 31],
        [ 1, 11],
        [ 5, 51]]])

In [12]:
a = np.array([[[1,2,3] , [3,4,5] , [5,6,7] ] , [[7,8,9] , [9,8,7] , [15,14,13]]])
a

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 5,  6,  7]],

       [[ 7,  8,  9],
        [ 9,  8,  7],
        [15, 14, 13]]])

In [18]:
b = np.array([[3,4,5],[5,6,7],[8,9,1]])
b
b[0,0] = 505
b[0,1] =434
b[0,2] =989
b[1,1 ] = 344
b

array([[505, 434, 989],
       [  5, 344,   7],
       [  8,   9,   1]])

In [23]:
np.append (b,[[1,1,2]], axis =0)

array([[505, 434, 989],
       [  5, 344,   7],
       [  8,   9,   1],
       [  1,   1,   2]])

In [27]:
b = np.append (b,[[1],[2],[3]], axis =1)
b

array([[505, 434, 989,   1,   1],
       [  5, 344,   7,   2,   2],
       [  8,   9,   1,   3,   3]])

In [4]:
import numpy as np
np.arange(11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(1,11,1.5)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [14]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
np.ones([4,5])
np.zeros([4,5])
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
p.dtype

NameError: name 'p' is not defined

In [34]:
p.astype(int)

NameError: name 'p' is not defined

In [25]:
np.random.randint(1,100,5)

array([51, 78, 84, 43, 19])

In [33]:
np.random.seed(5000)
np.random.randint(1,100,[3,5])

array([[28, 67, 98,  2, 30],
       [ 3, 15,  4, 97, 60],
       [27, 68, 47,  4, 65]])

In [32]:
np.random.seed(5000)

In [35]:
np.random.rand(3,4) * 100

array([[82.19188929, 32.24671905, 90.98561329, 92.65393055],
       [30.78515475,  3.66003632, 18.40615649, 62.0690298 ],
       [65.83740819, 31.15034218, 86.68766811, 13.2184136 ]])

In [38]:
 np.loadtxt('data.txt', dtype='str')

array([['its', 'new', 'file', 'new', 'data'],
       ['here', 'we', 'go', 'with', 'new']], dtype='<U4')

In [40]:
 np.loadtxt('data.txt', dtype='str')


array([['its', 'new', 'file', 'new', 'data'],
       ['here', 'we', 'go', 'with', 'new']], dtype='<U4')

In [44]:
np.savetxt('data1.txt', a, delimeter='|', fmt='%d')

NameError: name 'a' is not defined

In [45]:
np.savetxt('data1.txt',  delimeter='|', fmt='%d')

TypeError: savetxt() got an unexpected keyword argument 'delimeter'

In [49]:
a=np.array([[[4,41],[8,81],[7,71]]])
a

array([[[ 4, 41],
        [ 8, 81],
        [ 7, 71]]])

In [50]:
a.flatten()

array([ 4, 41,  8, 81,  7, 71])