a=10
print (type (a))

In [3]:
str="string using double quotes"

In [4]:
print('str')

str


In [1]:
s= '468hi3.4'
a= [4,6,8,'hi',5]
b= (4,6,8)
c= {4,6,8}
d={4:5,6:8,8:2}
type(a), type(b),type(c),type(d),type(s)

(list, tuple, set, dict, str)

In [4]:
b += ('svdl')

TypeError: can only concatenate tuple (not "str") to tuple

In [5]:
(*b,*b)

(4, 6, 8, 4, 6, 8)

In [3]:
a

[4, 6, 8, 'hi', 5, 'wfk']

In [2]:
a +=['wfk']

In [6]:
(*b,*s)

(4, 6, 8, '4', '6', '8', 'h', 'i', '3', '.', '4')

In [10]:
d

{4: 5, 6: 8, 8: 2, 'type': 'val'}

In [9]:
d['type'] ='val'

In [12]:
d2 ={'a':34, 'b':54}
print (d2)

{'a': 34, 'b': 54}


In [14]:
#s[0]='a'
a[0] ='a'

In [15]:
a

['a', 6, 8, 'hi', 5, 'wfk']

In [17]:
m = None

In [18]:
bool('rfvrs')

True

In [28]:
print(bool(''),
bool (['rbs']),
bool ({'sdvsz'}),
bool (()),
bool (-4),
bool(67),)

False True True False True True


In [24]:
d.find('')
d.strip('')
a.
b.
c.


(4, 6, 8)

In [3]:
'e'.join('hy')

'hey'

In [9]:
a=23
b=43
#using formatr specifier
c='hello %d and %d' %(a,b)
c
#using format function
c='hy {}and{}'
c=c.format(a,b)
c
#using f string
c=f'hy {a}and{b}'
c

'hy 23and43'

In [30]:
s= '468hi3.4'
a= [4,6,8,'hi',5]
b= (4,6,8)
c= {4,6,8}
d={4:5,6:8,8:2}
type(a), type(b),type(c),type(d),type(s)
e=['hey','hello','good','great','awesome']
e.sort()
e.sort(key=len, reverse=true)
e


NameError: name 'true' is not defined

In [31]:
e.sort(key=len, reverse=true)

NameError: name 'true' is not defined

In [29]:
list(d.keys())[0]
d.get('a','think')

'think'

In [ ]:
i=[1,2,3,4,5,6,7,8,9,0,]
i1=(set)

In [2]:
import numpy as np


In [3]:
b = np.array([[3,4,5],[5,6,7]])
b

array([[3, 4, 5],
       [5, 6, 7]])

In [8]:
c = np.array([[[4,41],[8,81],[7,71]]])
c

array([[[ 4, 41],
        [ 8, 81],
        [ 7, 71]]])

In [10]:
d = np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[3,31],[1,11],[5,51]]])
d

array([[[ 4, 41],
        [ 8, 81],
        [ 7, 71]],

       [[ 3, 31],
        [ 1, 11],
        [ 5, 51]]])

In [25]:
b = np.array([[3,4,5],[5,6,7],[13,14,51],[5,26,7]])
b


array([[ 3,  4,  5],
       [ 5,  6,  7],
       [13, 14, 51],
       [ 5, 26,  7]])

In [34]:
b[0:3,1:2]

array([[ 4],
       [ 6],
       [14]])